import { create } from 'zustand';
import { persist } from 'zustand/middleware';
export type BioStatus = '待分析' | '进行中' | '已完成' | '失败';
export type AuditStatus = '待审核' | '已审核' | '不通过';
export interface BioTask { id: string; sampleNo: string; productName: string; status: BioStatus; auditStatus: AuditStatus; pipeline?: string; startTime?: string; endTime?: string; }
export interface BioFilters { sampleNos?: string[]; productIds?: string[]; statuses?: BioStatus[]; auditStatuses?: AuditStatus[]; startRange?: [string, string]; endRange?: [string, string]; }
export interface PaginationConfig { current: number; pageSize: number; total: number; showSizeChanger: boolean; pageSizeOptions: string[]; }
interface State { tasks: BioTask[]; filteredTasks: BioTask[]; selectedRowKeys: string[]; filters: BioFilters; pagination: PaginationConfig; }
interface Actions { setFilters: (f: Partial<BioFilters>) => void; setPagination: (p: Partial<PaginationConfig>) => void; setSelectedRowKeys: (k: string[]) => void; query: () => void; start: (ids: string[]) => void; rerun: (ids: string[]) => void; audit: (ids: string[]) => void; }
const mock: BioTask[] = [ { id: 'b1', sampleNo: 'SMP001', productName: '外显子组测序', status: '待分析', auditStatus: '待审核', pipeline: 'WES-Pipeline' }, { id: 'b2', sampleNo: 'SMP020', productName: '肿瘤标志物检测', status: '已完成', auditStatus: '待审核', pipeline: 'Tumor-Pipeline', startTime: new Date(Date.now()-3600000).toISOString(), endTime: new Date().toISOString() } ];
const defaultFilters: BioFilters = { statuses: ['待分析','进行中','失败'], auditStatuses: ['待审核','已审核','不通过'] };
const defaultPagination: PaginationConfig = { current: 1, pageSize: 20, total: 0, showSizeChanger: true, pageSizeOptions: ['10','20','50','100'] };
export const useSpecialBioinfoStore = create<State & Actions>()(persist((set, get) => ({ tasks: mock, filteredTasks: [], selectedRowKeys: [], filters: defaultFilters, pagination: defaultPagination, setFilters: (f) => set((s) => ({ filters: { ...s.filters, ...f } })), setPagination: (p) => set((s) => ({ pagination: { ...s.pagination, ...p } })), setSelectedRowKeys: (k) => set({ selectedRowKeys: k }), query: () => { const { tasks, filters, pagination } = get(); let list = [...tasks]; if (filters.sampleNos?.length) list = list.filter(t => filters.sampleNos!.some(no => t.sampleNo.includes(no))); if (filters.productIds?.length) list = list.filter(t => filters.productIds!.some(pid => t.productName.includes(pid))); if (filters.statuses?.length) list = list.filter(t => filters.statuses!.includes(t.status)); if (filters.auditStatuses?.length) list = list.filter(t => filters.auditStatuses!.includes(t.auditStatus)); if (filters.startRange?.[0] && filters.startRange?.[1]) { const [st, et] = filters.startRange; list = list.filter(t => t.startTime ? new Date(t.startTime) >= new Date(st) && new Date(t.startTime) <= new Date(et) : false); } if (filters.endRange?.[0] && filters.endRange?.[1]) { const [st, et] = filters.endRange; list = list.filter(t => t.endTime ? new Date(t.endTime) >= new Date(st) && new Date(t.endTime) <= new Date(et) : false); } const startIdx = (pagination.current - 1) * pagination.pageSize; const page = list.slice(startIdx, startIdx + pagination.pageSize); set({ filteredTasks: page, pagination: { ...pagination, total: list.length } }); }, start: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, status: '进行中', startTime: new Date().toISOString() } : t) })); }, rerun: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, status: '进行中' } : t) })); }, audit: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, auditStatus: '已审核' } : t), selectedRowKeys: s.selectedRowKeys.filter(k => !ids.includes(k)) })); } }), { name: 'special-bioinfo-store', partialize: (s) => ({ tasks: s.tasks, filters: s.filters, pagination: s.pagination }) }));