import { create } from 'zustand';
import { persist } from 'zustand/middleware';
export type RunStatus = '待上机' | '运行中' | '暂停' | '结束' | '异常';
export interface SeqTask { id: string; batchNo: string; sampleNo: string; device: string; status: RunStatus; startTime?: string; endTime?: string; }
export interface SeqFilters { batchNos?: string[]; sampleNos?: string[]; devices?: string[]; statuses?: RunStatus[]; runRange?: [string, string]; }
export interface PaginationConfig { current: number; pageSize: number; total: number; showSizeChanger: boolean; pageSizeOptions: string[]; }
interface State { tasks: SeqTask[]; filteredTasks: SeqTask[]; selectedRowKeys: string[]; filters: SeqFilters; pagination: PaginationConfig; }
interface Actions { setFilters: (f: Partial<SeqFilters>) => void; setPagination: (p: Partial<PaginationConfig>) => void; setSelectedRowKeys: (k: string[]) => void; query: () => void; start: (ids: string[]) => void; pause: (ids: string[]) => void; finish: (ids: string[]) => void; }
const mock: SeqTask[] = [ { id: 's1', batchNo: 'B001', sampleNo: 'SMP001', device: 'NovaSeq X', status: '待上机' }, { id: 's2', batchNo: 'B002', sampleNo: 'SMP020', device: 'MGI T7', status: '运行中', startTime: new Date().toISOString() } ];
const defaultFilters: SeqFilters = { statuses: ['待上机','运行中','暂停','结束','异常'] };
const defaultPagination: PaginationConfig = { current: 1, pageSize: 20, total: 0, showSizeChanger: true, pageSizeOptions: ['10','20','50','100'] };
export const useSpecialSequencingStore = create<State & Actions>()(persist((set, get) => ({ tasks: mock, filteredTasks: [], selectedRowKeys: [], filters: defaultFilters, pagination: defaultPagination, setFilters: (f) => set((s) => ({ filters: { ...s.filters, ...f } })), setPagination: (p) => set((s) => ({ pagination: { ...s.pagination, ...p } })), setSelectedRowKeys: (k) => set({ selectedRowKeys: k }), query: () => { const { tasks, filters, pagination } = get(); let list = [...tasks]; if (filters.batchNos?.length) list = list.filter(t => filters.batchNos!.some(no => t.batchNo.includes(no))); if (filters.sampleNos?.length) list = list.filter(t => filters.sampleNos!.some(no => t.sampleNo.includes(no))); if (filters.devices?.length) list = list.filter(t => filters.devices!.includes(t.device)); if (filters.statuses?.length) list = list.filter(t => filters.statuses!.includes(t.status)); if (filters.runRange?.[0] && filters.runRange?.[1]) { const [st, et] = filters.runRange; list = list.filter(t => t.startTime ? new Date(t.startTime) >= new Date(st) && new Date(t.startTime) <= new Date(et) : false); } const startIdx = (pagination.current - 1) * pagination.pageSize; const page = list.slice(startIdx, startIdx + pagination.pageSize); set({ filteredTasks: page, pagination: { ...pagination, total: list.length } }); }, start: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, status: '运行中', startTime: new Date().toISOString() } : t) })); }, pause: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, status: '暂停' } : t) })); }, finish: (ids) => { set((s) => ({ tasks: s.tasks.map(t => ids.includes(t.id) ? { ...t, status: '结束', endTime: new Date().toISOString() } : t), selectedRowKeys: s.selectedRowKeys.filter(k => !ids.includes(k)) })); } }), { name: 'special-sequencing-store', partialize: (s) => ({ tasks: s.tasks, filters: s.filters, pagination: s.pagination }) }));