import { create } from 'zustand';
import { persist } from 'zustand/middleware';
export type TechRouteStatus = '待确认' | '已确认' | '退回';
export interface TechRouteTask { id: string; sampleNo: string; productName: string; routeName: string; status: TechRouteStatus; confirmer?: string; confirmTime?: string; arriveTime?: string; }
export interface TechRouteFilters { sampleNos?: string[]; productIds?: string[]; routeIds?: string[]; statuses?: TechRouteStatus[]; confirmRange?: [string, string]; arriveRange?: [string, string]; }
export interface PaginationConfig { current: number; pageSize: number; total: number; showSizeChanger: boolean; pageSizeOptions: string[]; }
interface State { tasks: TechRouteTask[]; filteredTasks: TechRouteTask[]; selectedRowKeys: string[]; filters: TechRouteFilters; pagination: PaginationConfig; loading: boolean; }
interface Actions { setTasks: (tasks: TechRouteTask[]) => void; setFilteredTasks: (tasks: TechRouteTask[]) => void; setSelectedRowKeys: (keys: string[]) => void; setFilters: (filters: Partial<TechRouteFilters>) => void; resetFilters: () => void; setPagination: (pagination: Partial<PaginationConfig>) => void; query: () => void; confirm: (ids: string[]) => void; cancel: (ids: string[]) => void; changeRoute: (ids: string[], newRoute: string) => void; }
const defaultFilters: TechRouteFilters = { statuses: ['待确认','已确认','退回'] };
const defaultPagination: PaginationConfig = { current: 1, pageSize: 20, total: 0, showSizeChanger: true, pageSizeOptions: ['10','20','50','100'] };
const mock: TechRouteTask[] = [ { id: 'tr1', sampleNo: 'SMP001', productName: '外显子组测序', routeName: 'WES标准路线', status: '待确认', arriveTime: new Date().toISOString() }, { id: 'tr2', sampleNo: 'SMP020', productName: '肿瘤标志物检测', routeName: '肿瘤标志物路线A', status: '已确认', confirmer: 'admin', confirmTime: new Date().toISOString(), arriveTime: new Date().toISOString() } ];
export const useTechRouteStore = create<State & Actions>()(persist((set, get) => ({ tasks: mock, filteredTasks: [], selectedRowKeys: [], filters: defaultFilters, pagination: defaultPagination, loading: false, setTasks: (tasks) => set({ tasks }), setFilteredTasks: (filteredTasks) => set({ filteredTasks }), setSelectedRowKeys: (selectedRowKeys) => set({ selectedRowKeys }), setFilters: (filters) => set((state) => ({ filters: { ...state.filters, ...filters } })), resetFilters: () => set({ filters: defaultFilters }), setPagination: (pagination) => set((state) => ({ pagination: { ...state.pagination, ...pagination } })), query: () => { const { tasks, filters, pagination } = get(); let list = [...tasks]; if (filters.sampleNos?.length) { list = list.filter(t => filters.sampleNos!.some(no => t.sampleNo.includes(no))); } if (filters.productIds?.length) { list = list.filter(t => filters.productIds!.some(pid => t.productName.includes(pid))); } if (filters.routeIds?.length) { list = list.filter(t => filters.routeIds!.some(rid => t.routeName.includes(rid))); } if (filters.statuses?.length) { list = list.filter(t => filters.statuses!.includes(t.status)); } if (filters.confirmRange?.[0] && filters.confirmRange?.[1]) { const [start, end] = filters.confirmRange; list = list.filter(t => t.confirmTime ? new Date(t.confirmTime) >= new Date(start) && new Date(t.confirmTime) <= new Date(end) : false); } if (filters.arriveRange?.[0] && filters.arriveRange?.[1]) { const [start, end] = filters.arriveRange; list = list.filter(t => t.arriveTime ? new Date(t.arriveTime) >= new Date(start) && new Date(t.arriveTime) <= new Date(end) : false); } list.sort((a, b) => (b.arriveTime ? new Date(b.arriveTime).getTime() : 0) - (a.arriveTime ? new Date(a.arriveTime).getTime() : 0)); const startIdx = (pagination.current - 1) * pagination.pageSize; const endIdx = startIdx + pagination.pageSize; const page = list.slice(startIdx, endIdx); set({ filteredTasks: page, pagination: { ...pagination, total: list.length } }); }, confirm: (ids) => { set((state) => ({ tasks: state.tasks.map(t => ids.includes(t.id) ? { ...t, status: '已确认', confirmer: 'admin', confirmTime: new Date().toISOString() } : t), selectedRowKeys: state.selectedRowKeys.filter(k => !ids.includes(k)) })); }, cancel: (ids) => { set((state) => ({ tasks: state.tasks.map(t => ids.includes(t.id) ? { ...t, status: '退回' } : t), selectedRowKeys: state.selectedRowKeys.filter(k => !ids.includes(k)) })); }, changeRoute: (ids, newRoute) => { set((state) => ({ tasks: state.tasks.map(t => ids.includes(t.id) ? { ...t, routeName: newRoute } : t) })); } }), { name: 'tech-route-store', partialize: (state) => ({ tasks: state.tasks, filters: state.filters, pagination: state.pagination }) }));
export type { State as TechRouteState, Actions as TechRouteActions };
